

urls =
["http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/corporate-war-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/false-lead-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/private-security-force-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/accelerated-beta-test-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/mandatory-upgrades-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/project-vitruvius-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/braintrust-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/fetal-ai-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/nisei-mk-ii-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/breaking-news-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/project-beale-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/government-contracts-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/hostile-takeover-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/posted-bounty-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/melange-mining-corp-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/pad-campaign-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/private-contracts-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/adonis-campaign-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/aggressive-secretary-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/encryption-protocol-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/eve-campaign-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/dedicated-server-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/edge-of-world-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/project-junebug-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ronin-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/snare-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/zaibatsu-loyalty-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ghost-branch-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/marked-accounts-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/dedicated-response-team-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/security-subcontract-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/chimera-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/draco-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/enigma-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/hunter-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/wall-of-static-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/eli-1-0-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/heimdall-1-0-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ichi-1-0-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/janus-1-0-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/rototurret-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sherlock-1-0-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/viktor-1-0-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/chum-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/neural-katana-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sensei-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/wall-of-thorns-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/data-hound-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/data-raven-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/flare-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/pop-up-window-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/tmi-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/tollbooth-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/uroboros-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/archer-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/burke-bugs-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/caduceus-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/hadrians-wall-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ice-wall-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/salvage-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/shadow-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/tyrant-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/woodcutter-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/foxfire-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/freelancer-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/hedge-fund-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/archived-memories-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/biotic-labor-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/shipment-from-mirrormorph-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/neural-emp-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/precognition-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/trick-of-light-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/anonymous-tip-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/closed-accounts-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sea-source-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/beanstalk-royalties-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/commercialization-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/oversight-ai-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/power-grid-overload-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/scorched-earth-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/corporate-troubleshooter-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/experiential-data-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/akitaro-watanabe-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/hokusai-grid-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/midori-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/bernice-mai-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/chilo-city-grid-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/red-herrings-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sansan-city-grid-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/amazon-industrial-zone-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/simone-diego-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/infiltration-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sure-gamble-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/deja-vu-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/surge-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/vamp-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/demolition-run-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/easy-mark-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/emergency-shutdown-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/forged-activation-orders-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/inside-job-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/networking-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/special-order-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/diesel-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/modded-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/notoriety-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/quality-time-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/test-run-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/the-makers-eye-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/tinkering-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/dyson-mem-chip-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/plascrete-carapace-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/cyberfeeder-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/grimoire-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/cortez-chip-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/doppelganger-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/e3-feedback-implants-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/lemuria-codecracker-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/akamatsu-mem-chip-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/dinosaurus-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/rabbit-hole-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/replicator-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/the-personal-touch-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/the-toolbox-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/corroder-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/darwin-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/datasucker-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/force-of-nature-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/imp-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/medium-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/morning-star-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/nerve-agent-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/parasite-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/wyrm-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/aurora-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/crescentus-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/femme-fatale-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ninja-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/peacock-what-lies-ahead",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/pheromones-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/battering-ram-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/creeper-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/deep-thought-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/deus-x-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/gordian-blade-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/magnum-opus-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/net-shield-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/access-to-globalsec-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/armitage-codebusting-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/inside-man-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/new-angeles-city-hall-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/public-sympathy-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/underworld-contact-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/data-leak-reversal-future-proof",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/ice-carver-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/joshua-b-cyber-exodus",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/liberated-account-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/scrubber-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/wyldside-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/xanadu-humanitys-shadow",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/bank-job-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/compromised-employee-trace-amount",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/crash-space-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/data-dealer-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/decoy-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/aesops-pawnshop-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/all-nighter-a-study-in-static",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/sacrificial-construct-core",
"http://www.cardgamedb.com/index.php/netrunner/android-netrunner-card-spoilers/_/the-helpful-ai-what-lies-ahead"]

require 'csv'

`touch cards.csv`
cards = CSV.read("cards.csv", :quote_char => '"')

def read_card(url)
  html = `curl -L #{url}`
  # puts html
  type = html.match(/(?mx)<b>Type:<\/b>\s*([^<]*)/)[1].strip
  set = html.match(/(?mx)<b>Set:<\/b>\s*([^:<]*)/)[1].strip
  number = html.match(/(?mx)<b>Number:<\/b>\s*([^:<]*)/)[1].strip
  {
    url: url,
    image_url:url.sub('/index.php/netrunner/android-netrunner-card-spoilers/_/','/forums/uploads/an/')+".png",
    type: type,
    set: set,
    number: number.to_i
  }
end

urls.each do |url|
  next if cards.map { |card| card[0] }.include?(url)
  puts url
  card = read_card(url)
  File.open('cards.csv', 'a') do |f|
    f.puts "\"#{card[:url]}\",\"#{card[:image_url]}\",\"#{card[:type]}\",\"#{card[:set]}\",#{card[:number]}"
  end
end
